[workspace]
resolver = "2"
members = [
	"chirpstack",
	"chirpstack-integration",
	"lrwn",
	"lrwn-filters",
	"backend",
	"api/rust",
]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1

[patch.crates-io]
diesel = { git = "https://github.com/diesel-rs/diesel.git", rev = "566dcccc6df6adb6ceddef8df5e1806e2a065c40" }
diesel-async = { git = "https://github.com/weiznich/diesel_async.git", rev = "017ebe2fb7a2709ab5db92148dea5ce812a35e09" }
